version: '3'

services:

  aspnetcore-docker-vscode.web:
    image: aspnetcore-docker-vscode.web
    build:
      context: ./
      dockerfile: Dockerfile.debug
    ports: 
    - "5001:80"
    volumes: 
      - ./:/app
      - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
      - ${ProgramFiles}/dotnet/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
    container_name: aspnetcore-docker-vscode.web